### ISSUE TITLE
Hello Author, I found the edgenn package in the nas_model.py and builder.py is missing，Can you provide a solution 

### ISSUE THREAD

**Issue by xjyp** [hunto/image_classification_sota#10]

**Comment by hunto** [comment]
Hi @xjyp ,

`edgenn` is an internal extension in our group to support NAS and pruning algorithms, and it is not planned to be public now.

For conventional imagenet training and all the released algorithms in `image_classification_sota`, you can run the code without `edgenn`.

If you want to use NAS and pruning algorithms, there is an alternative toolbox [MMRazor](https://github.com/open-mmlab/mmrazor) by OpenMMLab, you can try it :)

**Comment by xjyp** [comment]
Thank you for your kind reply,I get it
