### ISSUE TITLE
(dataset problem) ImageNet has not "meta/train.txt"

### ISSUE THREAD

**Issue by Azong-HQU** [hunto/image_classification_sota#3]
Hello author, the imagenet dataset I downloaded does not have a meta/train.txt file, can you provide me with a file?

**Comment by hunto** [comment]
Hi, thanks for your attention.

You can get the meta files through the link below:
http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz

Also, you can check the detailed instructions of preparing dataset in [mmcls docs](https://mmclassification.readthedocs.io/en/latest/getting_started.html) (thanks to the OpenMMLab team).
