### ISSUE TITLE
How to write the transformer decoder?

### ISSUE THREAD

**Issue by AndSonder** [hunto/image_classification_sota#7]
I want to use Lightvit to write the net structure like this : 

![image](https://user-images.githubusercontent.com/55493212/182013236-64eb24c5-b07b-45e6-b9f1-00fa6fb335eb.png)

Can you tell me how to write the decoder, please?

**Comment by hunto** [comment]
Hi @AndSonder ,

Thanks for your attention about our work. Unlike the plain ViT structure, our model downsamples the input images hierarchically in each stage, and finally encode the image with stride=32.

Therefore, to decode the image feature back to the original size, you may need to replace our `ResidualMergePatch` module with an upsample module. You can check the code in StyleSwin as an example for how to implement decoder in hierarchical ViTs: https://github.com/microsoft/StyleSwin/blob/9e39bb3afad1aa0124126f8ad319e1316b15a9db/models/generator.py#L366

If you have any question, please feel free to contact with me.

**Comment by AndSonder** [comment]
> Hi @AndSonder ,
> 
> Thanks for your attention about our work. Unlike the plain ViT structure, our model downsamples the input images hierarchically in each stage, and finally encode the image with stride=32.
> 
> Therefore, to decode the image feature back to the original size, you may need to replace our `ResidualMergePatch` module with an upsample module. You can check the code in StyleSwin as an example for how to implement decoder in hierarchical ViTs: https://github.com/microsoft/StyleSwin/blob/9e39bb3afad1aa0124126f8ad319e1316b15a9db/models/generator.py#L366
> 
> If you have any question, please feel free to contact with me.

Thank you very much! I will try it.
