### ISSUE TITLE
训练效果

### ISSUE THREAD

**Issue by dydxdt** [hunto/image_classification_sota#8]
您好，想问下提供的resnet或mobilnetv2结构，您有训练测试达到很高的acc吗？还是里面的参数需要自己继续调整。我直接用mbv2训练自己的分类任务，效果不是很好

**Comment by hunto** [comment]
Hi @dydxdt ,

config中提供的 [configs/strategies/MBV2/mbv2.yaml](https://github.com/hunto/image_classification_sota/blob/main/configs/strategies/MBV2/mbv2.yaml) 策略，是用于mbv2 imagenet训练的baseline策略，其精度大约在73.3%。使用 [configs/strategies/MBV2/mbv2_se_aa.yaml](https://github.com/hunto/image_classification_sota/blob/main/configs/strategies/MBV2/mbv2_se_aa.yaml)能得到约74.3%的精度，算是目前mbv2比较高的精度了。

同样，在resnet上，[configs/strategies/resnet/resnet.yam](https://github.com/hunto/image_classification_sota/blob/main/configs/strategies/resnet/resnet.yaml) 是与torchvision一致的baseline训练策略，精度大约在76.1%。[configs/strategies/resnet/seresnext.yaml](https://github.com/hunto/image_classification_sota/blob/main/configs/strategies/resnet/seresnext.yaml) 会更强一些，大约能到78.5%。

**对于你自己的数据集，这部分在imagenet上较高精度的策略不一定对你的任务最优。策略的调整取决于数据集大小、任务难度等特性，需要进行一些调参。**

**Comment by dydxdt** [comment]
感谢～
